# Generated by Django 5.1.2 on 2024-10-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reloj',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=5)),
                ('material', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
                ('ano_lanzamiento', models.DateField()),
            ],
        ),
    ]
